CREATE TABLE AEROLINEAENTITY (IDAEROLINEA INTEGER NOT NULL, aero_nom VARCHAR(255), PRIMARY KEY (IDAEROLINEA))
CREATE TABLE AEROPUERTOENTITY (IDAEROPUERTO INTEGER NOT NULL, CODIGO VARCHAR(255), NOMBRE VARCHAR(255), CIUDAD_IDCIUDAD INTEGER, PRIMARY KEY (IDAEROPUERTO))
CREATE TABLE ASIENTOENTITY (IDASIENTO INTEGER NOT NULL, NUMEROASIENTO VARCHAR(255), PRIMARY KEY (IDASIENTO))
CREATE TABLE ASIGNACIONENTITY (CODIGOASIGNACION VARCHAR(255) NOT NULL, ASIENTO_IDASIENTO INTEGER, PASAJERO_IDPASAJERO INTEGER, PRIMARY KEY (CODIGOASIGNACION))
CREATE TABLE AVIONENTITY (IDAVION INTEGER NOT NULL, MATRICULA VARCHAR(255), MODELO VARCHAR(255), PRIMARY KEY (IDAVION))
CREATE TABLE CIUDADENTITY (IDCIUDAD INTEGER NOT NULL, CODIGOPOSTAL VARCHAR(255), NOMBRE VARCHAR(255), PRIMARY KEY (IDCIUDAD))
CREATE TABLE PASAJEROENTITY (IDPASAJERO INTEGER NOT NULL, APELLIDO VARCHAR(255), CUIL VARCHAR(255), NOMBRES VARCHAR(255), TELEFONO VARCHAR(255), PRIMARY KEY (IDPASAJERO))
CREATE TABLE PILOTOENTITY (IDPILOTO INTEGER NOT NULL, APELLIDO VARCHAR(255), DOCUMENTO VARCHAR(255), FECHANACIMIENTO BYTEA, NOMBRES VARCHAR(255), PRIMARY KEY (IDPILOTO))
CREATE TABLE VUELOENTITY (CODIGOVUELO VARCHAR(255) NOT NULL, FECHAHORAARRIBO BYTEA, FECHAHORASALIDA BYTEA, AEROLINEA_IDAEROLINEA INTEGER, ARRIBO_IDAEROPUERTO INTEGER, AVION_IDAVION INTEGER, SALIDA_IDAEROPUERTO INTEGER, PRIMARY KEY (CODIGOVUELO))
CREATE TABLE AVIONENTITY_ASIENTOENTITY (AvionEntity_IDAVION INTEGER NOT NULL, listaAsientos_IDASIENTO INTEGER NOT NULL, PRIMARY KEY (AvionEntity_IDAVION, listaAsientos_IDASIENTO))
CREATE TABLE VUELOENTITY_ASIGNACIONENTITY (VueloEntity_CODIGOVUELO VARCHAR(255) NOT NULL, pasajeros_CODIGOASIGNACION VARCHAR(255) NOT NULL, PRIMARY KEY (VueloEntity_CODIGOVUELO, pasajeros_CODIGOASIGNACION))
CREATE TABLE VUELOENTITY_PILOTOENTITY (VueloEntity_CODIGOVUELO VARCHAR(255) NOT NULL, pilotos_IDPILOTO INTEGER NOT NULL, PRIMARY KEY (VueloEntity_CODIGOVUELO, pilotos_IDPILOTO))
ALTER TABLE AEROPUERTOENTITY ADD CONSTRAINT FK_AEROPUERTOENTITY_CIUDAD_IDCIUDAD FOREIGN KEY (CIUDAD_IDCIUDAD) REFERENCES CIUDADENTITY (IDCIUDAD)
ALTER TABLE ASIGNACIONENTITY ADD CONSTRAINT FK_ASIGNACIONENTITY_PASAJERO_IDPASAJERO FOREIGN KEY (PASAJERO_IDPASAJERO) REFERENCES PASAJEROENTITY (IDPASAJERO)
ALTER TABLE ASIGNACIONENTITY ADD CONSTRAINT FK_ASIGNACIONENTITY_ASIENTO_IDASIENTO FOREIGN KEY (ASIENTO_IDASIENTO) REFERENCES ASIENTOENTITY (IDASIENTO)
ALTER TABLE VUELOENTITY ADD CONSTRAINT FK_VUELOENTITY_SALIDA_IDAEROPUERTO FOREIGN KEY (SALIDA_IDAEROPUERTO) REFERENCES AEROPUERTOENTITY (IDAEROPUERTO)
ALTER TABLE VUELOENTITY ADD CONSTRAINT FK_VUELOENTITY_ARRIBO_IDAEROPUERTO FOREIGN KEY (ARRIBO_IDAEROPUERTO) REFERENCES AEROPUERTOENTITY (IDAEROPUERTO)
ALTER TABLE VUELOENTITY ADD CONSTRAINT FK_VUELOENTITY_AEROLINEA_IDAEROLINEA FOREIGN KEY (AEROLINEA_IDAEROLINEA) REFERENCES AEROLINEAENTITY (IDAEROLINEA)
ALTER TABLE VUELOENTITY ADD CONSTRAINT FK_VUELOENTITY_AVION_IDAVION FOREIGN KEY (AVION_IDAVION) REFERENCES AVIONENTITY (IDAVION)
ALTER TABLE AVIONENTITY_ASIENTOENTITY ADD CONSTRAINT FK_AVIONENTITY_ASIENTOENTITY_AvionEntity_IDAVION FOREIGN KEY (AvionEntity_IDAVION) REFERENCES AVIONENTITY (IDAVION)
ALTER TABLE AVIONENTITY_ASIENTOENTITY ADD CONSTRAINT FK_AVIONENTITY_ASIENTOENTITY_listaAsientos_IDASIENTO FOREIGN KEY (listaAsientos_IDASIENTO) REFERENCES ASIENTOENTITY (IDASIENTO)
ALTER TABLE VUELOENTITY_ASIGNACIONENTITY ADD CONSTRAINT FK_VUELOENTITY_ASIGNACIONENTITY_VueloEntity_CODIGOVUELO FOREIGN KEY (VueloEntity_CODIGOVUELO) REFERENCES VUELOENTITY (CODIGOVUELO)
ALTER TABLE VUELOENTITY_ASIGNACIONENTITY ADD CONSTRAINT FK_VUELOENTITY_ASIGNACIONENTITY_pasajeros_CODIGOASIGNACION FOREIGN KEY (pasajeros_CODIGOASIGNACION) REFERENCES ASIGNACIONENTITY (CODIGOASIGNACION)
ALTER TABLE VUELOENTITY_PILOTOENTITY ADD CONSTRAINT FK_VUELOENTITY_PILOTOENTITY_VueloEntity_CODIGOVUELO FOREIGN KEY (VueloEntity_CODIGOVUELO) REFERENCES VUELOENTITY (CODIGOVUELO)
ALTER TABLE VUELOENTITY_PILOTOENTITY ADD CONSTRAINT FK_VUELOENTITY_PILOTOENTITY_pilotos_IDPILOTO FOREIGN KEY (pilotos_IDPILOTO) REFERENCES PILOTOENTITY (IDPILOTO)
CREATE SEQUENCE asignacion_seq START WITH 1
CREATE SEQUENCE aeropuerto_seq START WITH 1
CREATE SEQUENCE vuelo_seq START WITH 1
CREATE SEQUENCE ciudad_seq START WITH 1
CREATE SEQUENCE piloto_seq START WITH 1
CREATE SEQUENCE asiento_seq START WITH 1
CREATE SEQUENCE pasajero_seq START WITH 1
CREATE SEQUENCE aerolinea_seq START WITH 1
CREATE SEQUENCE avion_seq START WITH 1
