CREATE TABLE VISITA (IDVISITA BIGINT NOT NULL, FECHAVISITA BYTEA, PESOVISITA FLOAT, MOTIVOVISITA_IDMOTIVOVISITA BIGINT, PRIMARY KEY (IDVISITA))
CREATE TABLE ENFERMEDADPACIENTE (IDENFERMEDADPACIENTE BIGINT NOT NULL, FECHAENFERMEDAD BYTEA, ENFERMEDAD_IDENFERMEDAD BIGINT, PRIMARY KEY (IDENFERMEDADPACIENTE))
CREATE TABLE PACIENTE (IDPACIENTE BIGINT NOT NULL, ALIAS VARCHAR(255), COLORPELO VARCHAR(255), FECHANACIMIENTO BYTEA, PESOACTUAL FLOAT, DUENIO_IDCLIENTE BIGINT, RAZA_IDRAZA BIGINT, PRIMARY KEY (IDPACIENTE))
CREATE TABLE MOTIVOVISITA (IDMOTIVOVISITA BIGINT NOT NULL, DESCRIPCION VARCHAR(255), PRIMARY KEY (IDMOTIVOVISITA))
CREATE TABLE LOCALIDAD (IDLOCALIDAD BIGINT NOT NULL, CODIGOPOSTAL VARCHAR(255), NOMBRE VARCHAR(255), PRIMARY KEY (IDLOCALIDAD))
CREATE TABLE ENFERMEDAD (IDENFERMEDAD BIGINT NOT NULL, NOMBREENFERNEDAD VARCHAR(255), PRIMARY KEY (IDENFERMEDAD))
CREATE TABLE CLIENTE (IDCLIENTE BIGINT NOT NULL, APELLIDOFAMILIA VARCHAR(255), NROCUENTA VARCHAR(255), TELEFONO VARCHAR(255), DOMICILIO_IDDOMICILIO BIGINT, PRIMARY KEY (IDCLIENTE))
CREATE TABLE VACUNACOLOCADA (IDVACUNACOLOCADA BIGINT NOT NULL, FECHACOLOCACION BYTEA, ENFERMEDAD_IDENFERMEDAD BIGINT, PRIMARY KEY (IDVACUNACOLOCADA))
CREATE TABLE ESPECIE (IDESPECIE BIGINT NOT NULL, NOMBRE VARCHAR(255), PRIMARY KEY (IDESPECIE))
CREATE TABLE DOMICILIO (IDDOMICILIO BIGINT NOT NULL, CALLE VARCHAR(255), DEPARTAMENTO VARCHAR(255), NUMERO INTEGER, PISO INTEGER, LOCALIDAD_IDLOCALIDAD BIGINT, PRIMARY KEY (IDDOMICILIO))
CREATE TABLE MEDICACION (IDMEDICACION BIGINT NOT NULL, DOSIS VARCHAR(255), INTERVALO INTEGER, PERIODO VARCHAR(255), MEDICAMENTO_IDMEDICAMENTO BIGINT, PRIMARY KEY (IDMEDICACION))
CREATE TABLE RAZA (IDRAZA BIGINT NOT NULL, NOMBRE VARCHAR(255), ESPECIE_IDESPECIE BIGINT, PRIMARY KEY (IDRAZA))
CREATE TABLE MEDICAMENTO (IDMEDICAMENTO BIGINT NOT NULL, CODIGO VARCHAR(255), NOMBRE VARCHAR(255), PRIMARY KEY (IDMEDICAMENTO))
CREATE TABLE ENFERMEDADPACIENTE_MEDICACION (EnfermedadPaciente_IDENFERMEDADPACIENTE BIGINT NOT NULL, medicacion_IDMEDICACION BIGINT NOT NULL, PRIMARY KEY (EnfermedadPaciente_IDENFERMEDADPACIENTE, medicacion_IDMEDICACION))
CREATE TABLE PACIENTE_ENFERMEDADPACIENTE (Paciente_IDPACIENTE BIGINT NOT NULL, enfermedades_IDENFERMEDADPACIENTE BIGINT NOT NULL, PRIMARY KEY (Paciente_IDPACIENTE, enfermedades_IDENFERMEDADPACIENTE))
CREATE TABLE PACIENTE_VACUNACOLOCADA (Paciente_IDPACIENTE BIGINT NOT NULL, vacunas_IDVACUNACOLOCADA BIGINT NOT NULL, PRIMARY KEY (Paciente_IDPACIENTE, vacunas_IDVACUNACOLOCADA))
CREATE TABLE PACIENTE_VISITA (Paciente_IDPACIENTE BIGINT NOT NULL, visitas_IDVISITA BIGINT NOT NULL, PRIMARY KEY (Paciente_IDPACIENTE, visitas_IDVISITA))
ALTER TABLE VISITA ADD CONSTRAINT FK_VISITA_MOTIVOVISITA_IDMOTIVOVISITA FOREIGN KEY (MOTIVOVISITA_IDMOTIVOVISITA) REFERENCES MOTIVOVISITA (IDMOTIVOVISITA)
ALTER TABLE ENFERMEDADPACIENTE ADD CONSTRAINT FK_ENFERMEDADPACIENTE_ENFERMEDAD_IDENFERMEDAD FOREIGN KEY (ENFERMEDAD_IDENFERMEDAD) REFERENCES ENFERMEDAD (IDENFERMEDAD)
ALTER TABLE PACIENTE ADD CONSTRAINT FK_PACIENTE_RAZA_IDRAZA FOREIGN KEY (RAZA_IDRAZA) REFERENCES RAZA (IDRAZA)
ALTER TABLE PACIENTE ADD CONSTRAINT FK_PACIENTE_DUENIO_IDCLIENTE FOREIGN KEY (DUENIO_IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE)
ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_DOMICILIO_IDDOMICILIO FOREIGN KEY (DOMICILIO_IDDOMICILIO) REFERENCES DOMICILIO (IDDOMICILIO)
ALTER TABLE VACUNACOLOCADA ADD CONSTRAINT FK_VACUNACOLOCADA_ENFERMEDAD_IDENFERMEDAD FOREIGN KEY (ENFERMEDAD_IDENFERMEDAD) REFERENCES ENFERMEDAD (IDENFERMEDAD)
ALTER TABLE DOMICILIO ADD CONSTRAINT FK_DOMICILIO_LOCALIDAD_IDLOCALIDAD FOREIGN KEY (LOCALIDAD_IDLOCALIDAD) REFERENCES LOCALIDAD (IDLOCALIDAD)
ALTER TABLE MEDICACION ADD CONSTRAINT FK_MEDICACION_MEDICAMENTO_IDMEDICAMENTO FOREIGN KEY (MEDICAMENTO_IDMEDICAMENTO) REFERENCES MEDICAMENTO (IDMEDICAMENTO)
ALTER TABLE RAZA ADD CONSTRAINT FK_RAZA_ESPECIE_IDESPECIE FOREIGN KEY (ESPECIE_IDESPECIE) REFERENCES ESPECIE (IDESPECIE)
ALTER TABLE ENFERMEDADPACIENTE_MEDICACION ADD CONSTRAINT FK_ENFERMEDADPACIENTE_MEDICACION_medicacion_IDMEDICACION FOREIGN KEY (medicacion_IDMEDICACION) REFERENCES MEDICACION (IDMEDICACION)
ALTER TABLE ENFERMEDADPACIENTE_MEDICACION ADD CONSTRAINT NFRMEDADPACIENTEMEDICACIONnfermedadPacienteIDENFERMEDADPACIENTE FOREIGN KEY (EnfermedadPaciente_IDENFERMEDADPACIENTE) REFERENCES ENFERMEDADPACIENTE (IDENFERMEDADPACIENTE)
ALTER TABLE PACIENTE_ENFERMEDADPACIENTE ADD CONSTRAINT PACIENTE_ENFERMEDADPACIENTE_enfermedades_IDENFERMEDADPACIENTE FOREIGN KEY (enfermedades_IDENFERMEDADPACIENTE) REFERENCES ENFERMEDADPACIENTE (IDENFERMEDADPACIENTE)
ALTER TABLE PACIENTE_ENFERMEDADPACIENTE ADD CONSTRAINT FK_PACIENTE_ENFERMEDADPACIENTE_Paciente_IDPACIENTE FOREIGN KEY (Paciente_IDPACIENTE) REFERENCES PACIENTE (IDPACIENTE)
ALTER TABLE PACIENTE_VACUNACOLOCADA ADD CONSTRAINT FK_PACIENTE_VACUNACOLOCADA_vacunas_IDVACUNACOLOCADA FOREIGN KEY (vacunas_IDVACUNACOLOCADA) REFERENCES VACUNACOLOCADA (IDVACUNACOLOCADA)
ALTER TABLE PACIENTE_VACUNACOLOCADA ADD CONSTRAINT FK_PACIENTE_VACUNACOLOCADA_Paciente_IDPACIENTE FOREIGN KEY (Paciente_IDPACIENTE) REFERENCES PACIENTE (IDPACIENTE)
ALTER TABLE PACIENTE_VISITA ADD CONSTRAINT FK_PACIENTE_VISITA_Paciente_IDPACIENTE FOREIGN KEY (Paciente_IDPACIENTE) REFERENCES PACIENTE (IDPACIENTE)
ALTER TABLE PACIENTE_VISITA ADD CONSTRAINT FK_PACIENTE_VISITA_visitas_IDVISITA FOREIGN KEY (visitas_IDVISITA) REFERENCES VISITA (IDVISITA)
CREATE SEQUENCE medicamento_id_seq START WITH 1
CREATE SEQUENCE medicacion_id_seq START WITH 1
CREATE SEQUENCE enfermedad_id_seq START WITH 1
CREATE SEQUENCE enfermedadpaciente_id_seq START WITH 1
CREATE SEQUENCE visita_id_seq START WITH 1
CREATE SEQUENCE cliente_id_seq START WITH 1
CREATE SEQUENCE localidad_id_seq START WITH 1
CREATE SEQUENCE paciente_id_seq START WITH 1
CREATE SEQUENCE motivovisita_id_seq START WITH 1
CREATE SEQUENCE raza_id_seq START WITH 1
CREATE SEQUENCE vacunacolocada_id_seq START WITH 1
CREATE SEQUENCE especie_id_seq START WITH 1
CREATE SEQUENCE domicilio_id_seq START WITH 1
